# Core package changes
"core":
  - changed-files:
    - any-glob-to-any-file: 'swiss_knife/core.py'

# Module-specific labels
"file-management":
  - changed-files:
    - any-glob-to-any-file: 'swiss_knife/file_management/**'

"text-processing":
  - changed-files:
    - any-glob-to-any-file: 'swiss_knife/text_processing/**'

"automation":
  - changed-files:
    - any-glob-to-any-file: 'swiss_knife/automation/**'

"cli":
  - changed-files:
    - any-glob-to-any-file: 'swiss_knife/cli/**'

# Test changes
"tests":
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

# Documentation changes
"documentation":
  - changed-files:
    - any-glob-to-any-file: 
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'

# Configuration changes
"configuration":
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - '.github/**'

# Dependencies
"dependencies":
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
