file-management:
  - changed-files:
      - any-glob-to-any-file:
        - 'swiss_knife/file_management/**/*'
        - 'tests/test_*file*.py'
        - 'tests/test_*duplicate*.py'
        - 'tests/test_*rename*.py'

text-processing:
  - changed-files:
      - any-glob-to-any-file:
        - 'swiss_knife/text_processing/**/*'
        - 'tests/test_*csv*.py'
        - 'tests/test_*text*.py'

automation-security:
  - changed-files:
      - any-glob-to-any-file:
        - 'swiss_knife/automation/**/*'
        - 'tests/test_*password*.py'
        - 'tests/test_*security*.py'

cli:
  - changed-files:
      - any-glob-to-any-file:
        - 'swiss_knife/cli/**/*'
        - 'tests/test_cli*.py'

core:
  - changed-files:
      - any-glob-to-any-file:
        - 'swiss_knife/core.py'
        - 'tests/test_core.py'

documentation:
  - changed-files:
      - any-glob-to-any-file:
        - 'README.md'
        - 'docs/**/*'
        - '**/*.md'

testing:
  - changed-files:
      - any-glob-to-any-file:
        - 'tests/**/*'
        - 'pytest.ini'
        - 'pyproject.toml'

ci:
  - changed-files:
      - any-glob-to-any-file:
        - '.github/workflows/**/*'
        - '.github/CODEOWNERS'
        - 'pyproject.toml'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
        - 'pyproject.toml'
        - 'requirements*.txt'
