codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70..100"
  status:
    project:
      default:
        target: 80
        threshold: "1%"
        base: "auto"
        branches: []
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: 80
        threshold: "1%"
        base: "auto"
        branches: []
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    changes:
      default:
        target: 80
        threshold: "1%"
        base: "auto"
        branches: []
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  hide_pr_type: false
  show_carryforward_flags: false

flags:
  unit:
    carryforward: true
    paths:
      - swiss_knife/
  integration:
    carryforward: true
    paths:
      - tests/

ignore:
  - "tests/**/*"
  - "setup.py"
  - "**/test_*.py"
