#!/bin/bash
# Duplicate Finder Usage Examples
# ================================
# Practical examples for using the duplicate finder script

echo "Sacred Scripts - Duplicate Finder Examples"
echo "=========================================="

# Set the script path
SCRIPT="python3 file_management/duplicate_finder.py"

echo -e "\n1. BASIC DUPLICATE DETECTION"
echo "----------------------------"
echo "# Find all duplicates in current directory"
echo "$SCRIPT ."
echo ""
echo "# Find duplicates in specific folder"
echo "$SCRIPT ~/Documents"
echo ""
echo "# Scan multiple directories at once"
echo "$SCRIPT ~/Documents ~/Downloads ~/Desktop"

echo -e "\n2. SIZE-BASED FILTERING"
echo "----------------------"
echo "# Find only large duplicates (>10MB)"
echo "$SCRIPT ~/Videos --min-size 10MB"
echo ""
echo "# Find small duplicates (<1MB)"
echo "$SCRIPT ~/Documents --max-size 1MB"
echo ""
echo "# Find duplicates in specific size range"
echo "$SCRIPT ~/Music --min-size 1MB --max-size 100MB"

echo -e "\n3. FILE TYPE FILTERING"
echo "---------------------"
echo "# Find duplicate images"
echo "$SCRIPT ~/Pictures --extensions jpg,jpeg,png,gif,bmp"
echo ""
echo "# Find duplicate videos"
echo "$SCRIPT ~/Videos --extensions mp4,avi,mkv,mov,wmv"
echo ""
echo "# Find duplicate documents"
echo "$SCRIPT ~/Documents --extensions pdf,docx,xlsx,pptx,txt"
echo ""
echo "# Find duplicate code files"
echo "$SCRIPT ~/Projects --extensions py,js,ts,java,cpp,c,h"

echo -e "\n4. HASH ALGORITHM OPTIONS"
echo "------------------------"
echo "# Fast scanning with MD5 (default)"
echo "$SCRIPT ~/Downloads --hash md5"
echo ""
echo "# Secure scanning with SHA256"
echo "$SCRIPT ~/Important --hash sha256"
echo ""
echo "# Maximum security with SHA512"
echo "$SCRIPT ~/Confidential --hash sha512"

echo -e "\n5. OUTPUT AND REPORTING"
echo "----------------------"
echo "# Save results as JSON"
echo "$SCRIPT ~/Documents --output json --file duplicates_report.json"
echo ""
echo "# Save detailed text report"
echo "$SCRIPT ~/Downloads --output text --file duplicates.txt"
echo ""
echo "# Scan and display statistics only"
echo "$SCRIPT ~/Pictures | head -20"

echo -e "\n6. SAFE DUPLICATE REMOVAL"
echo "-------------------------"
echo "# Preview what would be deleted (DRY RUN)"
echo "$SCRIPT ~/temp --delete-duplicates --dry-run"
echo ""
echo "# Delete duplicates, keep first file found"
echo "$SCRIPT ~/temp --delete-duplicates --keep-strategy first"
echo ""
echo "# Delete duplicates, keep file with shortest name"
echo "$SCRIPT ~/temp --delete-duplicates --keep-strategy shortest_name"
echo ""
echo "# Delete duplicates, keep file with longest name"
echo "$SCRIPT ~/temp --delete-duplicates --keep-strategy longest_name"

echo -e "\n7. ADVANCED COMBINATIONS"
echo "------------------------"
echo "# Find large image duplicates and export to JSON"
echo "$SCRIPT ~/Pictures --extensions jpg,png --min-size 5MB --output json --file large_image_dups.json"
echo ""
echo "# Secure scan of documents with detailed reporting"
echo "$SCRIPT ~/Documents --hash sha256 --extensions pdf,docx --output text --file secure_doc_scan.txt"
echo ""
echo "# Clean up temp directory (with confirmation)"
echo "$SCRIPT ~/temp --delete-duplicates --dry-run"
echo "# If satisfied with preview:"
echo "$SCRIPT ~/temp --delete-duplicates --keep-strategy shortest_name"

echo -e "\n8. PERFORMANCE OPTIMIZATION"
echo "---------------------------"
echo "# Fast scan of large directories (MD5 + size filter)"
echo "$SCRIPT ~/Videos --hash md5 --min-size 100MB"
echo ""
echo "# Targeted scan for specific file types only"
echo "$SCRIPT ~/Downloads --extensions zip,rar,7z,tar.gz"

echo -e "\n9. REAL-WORLD SCENARIOS"
echo "----------------------"
echo "# Clean up Downloads folder"
echo "$SCRIPT ~/Downloads --delete-duplicates --dry-run"
echo ""
echo "# Find duplicate photos from multiple cameras"
echo "$SCRIPT ~/Pictures/Camera1 ~/Pictures/Camera2 --extensions jpg,raw"
echo ""
echo "# Archive duplicate documents before deletion"
echo "$SCRIPT ~/Documents --output json --file backup_before_cleanup.json"
echo "$SCRIPT ~/Documents --delete-duplicates --keep-strategy first"
echo ""
echo "# Find space-wasting video duplicates"
echo "$SCRIPT ~/Movies ~/Videos --min-size 500MB --hash md5"

echo -e "\n10. AUTOMATION EXAMPLES"
echo "-----------------------"
echo "# Weekly cleanup script"
echo "#!/bin/bash"
echo "# Save report first"
echo "$SCRIPT ~/Downloads --output json --file weekly_dups_\$(date +%Y%m%d).json"
echo "# Clean if safe"
echo "$SCRIPT ~/Downloads --delete-duplicates --keep-strategy shortest_name"
echo ""
echo "# Monthly deep scan"
echo "$SCRIPT ~ --min-size 10MB --output text --file monthly_large_dups.txt"

echo -e "\nNOTE: Always use --dry-run before actual deletion!"
echo "      Keep backups of important data!"
